[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false
headless = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[client]
showErrorDetails = true
caching = false
displayEnabled = true
toolbarMode = "minimal"

[runner]
magicEnabled = true
installTracer = true
fixMatplotlib = true
fastReruns = true

[logger]
level = "info" 